export const initialDeck = [
  {
    id: 1,
    name: "SCARLET REVENANT",
    rarity: "COMMON",
    type: "ASHEN ORDER",
    attack: 6,
    defense: 5,
    description: "If Scarlet Revenant is the last character on your field, it gains +2 Attack and +2 Defense.",
    cardType: "UNIT",
    manaCost: 5,
    imagePath: "/placeholder.svg?height=300&width=200",
  },
  {
    id: 2,
    name: "GHOST OPERATIVE",
    rarity: "LEGENDARY",
    type: "ZERO DIVISION",
    attack: 4,
    defense: 7,
    description: "This unit cannot be targeted by enemy spells or abilities while cloaked.",
    special: "HOLOGRAPHIC",
    cardType: "UNIT",
    manaCost: 6,
    imagePath: "/placeholder.svg?height=300&width=200",
  },
  {
    id: 3,
    name: "REFLEX ENHANCER",
    rarity: "EPIC",
    type: "SHINOBYTE",
    attack: 3,
    defense: 4,
    description:
      "Grants +1 Speed and +1 Dodge when equipped to a Shinobyte character. Counterattack (deal 1 damage when targeted by an attack once per turn).",
    cardType: "UNIT",
    manaCost: 3,
    imagePath: "/placeholder.svg?height=300&width=200",
  },
  {
    id: 4,
    name: "ENERGY CORE",
    rarity: "NEUTRAL",
    type: "BOOST",
    attack: 2,
    defense: 2,
    description: "Attach to any character. It gains +1 ATK and can use abilities twice per turn.",
    cardType: "UNIT",
    manaCost: 2,
    imagePath: "/placeholder.svg?height=300&width=200",
  },
  {
    id: 5,
    name: "REGENERATION",
    rarity: "RARE",
    type: "NOVA SYNTH",
    description: "Restore 2 HP to one of your characters.",
    cardType: "SPELL",
    manaCost: 2,
    imagePath: "/placeholder.svg?height=300&width=200",
  },
  {
    id: 6,
    name: "NEURAL INTERFACE",
    rarity: "EPIC",
    type: "SHINOBYTE",
    attack: 3,
    defense: 3,
    description: "When played, draw a card. If it's a Shinobyte card, reduce its cost by 1.",
    cardType: "UNIT",
    manaCost: 3,
    imagePath: "/placeholder.svg?height=300&width=200",
  },
  {
    id: 7,
    name: "TACTICAL STRIKE",
    rarity: "COMMON",
    type: "ASHEN ORDER",
    description: "Deal 3 damage to an enemy unit.",
    cardType: "SPELL",
    manaCost: 2,
    imagePath: "/placeholder.svg?height=300&width=200",
  },
  {
    id: 8,
    name: "CYBER MONK",
    rarity: "COMMON",
    type: "ASHEN ORDER",
    attack: 2,
    defense: 4,
    description: "When played, reduce the cost of the next spell you play this turn by 1.",
    cardType: "UNIT",
    manaCost: 3,
    imagePath: "/placeholder.svg?height=300&width=200",
  },
  {
    id: 9,
    name: "QUANTUM SHIELD",
    rarity: "RARE",
    type: "ZERO DIVISION",
    description: "Target unit gains +0/+3 and cannot be targeted by spells until your next turn.",
    cardType: "SPELL",
    manaCost: 2,
    imagePath: "/placeholder.svg?height=300&width=200",
  },
  {
    id: 10,
    name: "STEALTH DRONE",
    rarity: "COMMON",
    type: "ZERO DIVISION",
    attack: 1,
    defense: 1,
    description: "Cannot be targeted by enemy abilities. Draw a card when this unit attacks.",
    cardType: "UNIT",
    manaCost: 1,
    imagePath: "/placeholder.svg?height=300&width=200",
  },
  {
    id: 11,
    name: "EMP BLAST",
    rarity: "EPIC",
    type: "NOVA SYNTH",
    description: "Disable all enemy units for 1 turn (they cannot attack or use abilities).",
    cardType: "SPELL",
    manaCost: 4,
    imagePath: "/placeholder.svg?height=300&width=200",
  },
  {
    id: 12,
    name: "MANA SURGE",
    rarity: "NEUTRAL",
    type: "BOOST",
    description: "Gain 2 mana crystals this turn only.",
    cardType: "SPELL",
    manaCost: 1,
    imagePath: "/placeholder.svg?height=300&width=200",
  },
  {
    id: 13,
    name: "CYBER ASSASSIN",
    rarity: "RARE",
    type: "SHINOBYTE",
    attack: 5,
    defense: 2,
    description: "When this unit destroys an enemy unit, it can attack again this turn.",
    cardType: "UNIT",
    manaCost: 4,
    imagePath: "/placeholder.svg?height=300&width=200",
  },
  {
    id: 14,
    name: "DATA CORRUPTION",
    rarity: "LEGENDARY",
    type: "NOVA SYNTH",
    description: "Take control of an enemy unit with 3 or less attack until the end of your next turn.",
    cardType: "SPELL",
    manaCost: 5,
    imagePath: "/placeholder.svg?height=300&width=200",
  },
  {
    id: 15,
    name: "HOLOGRAPHIC DECOY",
    rarity: "COMMON",
    type: "ZERO DIVISION",
    attack: 0,
    defense: 3,
    description: "Enemy units must attack this unit if able.",
    cardType: "UNIT",
    manaCost: 2,
    imagePath: "/placeholder.svg?height=300&width=200",
  },
]

// Shuffle deck function
export function shuffleDeck(deck) {
  const newDeck = [...deck]
  for (let i = newDeck.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[newDeck[i], newDeck[j]] = [newDeck[j], newDeck[i]]
  }
  return newDeck
}
